services:

  _defaults:
    autowire: true
    autoconfigure: true

  Micayael\Bundle\FormGeneratorBundle\Service\TestService: ~
  Micayael\Bundle\FormGeneratorBundle\Service\FormGenerator:
    arguments: ['@form.factory']
  Micayael\Bundle\FormGeneratorBundle\Config\SupportedTypes: ~

  micayael.form_generator:
    alias: Micayael\Bundle\FormGeneratorBundle\Service\FormGenerator
    public: true
