# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony 5

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} on ${{ matrix.operating-system }}
    strategy:
      fail-fast: true
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.4', '8.0', '8.1' ]
        symfony: [ '5.1.*', '5.2.*', '5.3.*', '5.4.*' ]

    steps:

      #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
      # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
      # name: Setup PHP ${{ matrix.php }}uses: shivammathur/setup-php@v2
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--no-progress --prefer-dist --optimize-autoloader"

      - name: Test symfony security
        if: runner.os == 'Linux'
        uses: symfonycorp/security-checker-action@v4
        with:
          disable-exit-code: 1
        id: security-check
      - name: Display the vulnerabilities as JSON
        if: runner.os == 'Linux'
        run: echo ${{ steps.security-check.outputs.vulns }}

      - name: Run test suite
        env:
          SYMFONY_DEPRECATIONS_HELPER: disabled
        run: vendor/bin/phpunit
